name: flutter_html_all
description: All optional flutter_html widgets, bundled into a single package.
version: 3.0.0-alpha.6
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  #  flutter_html: ^3.0.0-alpha.7
  #  flutter_html_audio: ^3.0.0-alpha.4
  #  flutter_html_iframe: ^3.0.0-alpha.4
  #  flutter_html_math: ^3.0.0-alpha.4
  #  flutter_html_svg: ^3.0.0-alpha.4
  #  flutter_html_table: ^3.0.0-alpha.4
  #  flutter_html_video: ^3.0.0-alpha.5
  flutter_html:
    git:
      url: https://github.com/robotoss/flutter_html
      ref: feature/temp_plugin_use
  flutter_html_audio:
    git:
      url: https://github.com/robotoss/flutter_html
      path: packages/flutter_html_audio
      ref: feature/temp_plugin_use
  flutter_html_iframe:
    git:
      url: https://github.com/robotoss/flutter_html
      path: packages/flutter_html_iframe
      ref: feature/temp_plugin_use
  flutter_html_math:
    git:
      url: https://github.com/robotoss/flutter_html
      path: packages/flutter_html_math
      ref: feature/temp_plugin_use
  flutter_html_svg:
    git:
      url: https://github.com/robotoss/flutter_html
      path: packages/flutter_html_svg
      ref: feature/temp_plugin_use
  flutter_html_table:
    git:
      url: https://github.com/robotoss/flutter_html
      path: packages/flutter_html_table
      ref: feature/temp_plugin_use
  flutter_html_video:
    git:
      url: https://github.com/robotoss/flutter_html
      path: packages/flutter_html_video
      ref: feature/temp_plugin_use

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
